version: 0.2

phases:
  install:
    commands:
      - printenv
  build:
    commands:
      - cabal new-build
      - cabal new-exec site build
artifacts:
  base-directory: '_site'
  files:
    - '**/*'